version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: 'mysql-container'
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev1234
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: dev1234
      MYSQL_PASSWORD: dev1234