version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: esdata01
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - monitoring

  kibana-local:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  esdata01:
    driver: local
    driver_opts:
      type: none
      device: ./data/
      o: bind